### PR TITLE
Fix compile issue with 5.1

### PR DESCRIPTION
**Pull request by ameaninglessname**

### CODE REVIEW

**Review by mastercoms — CHANGES_REQUESTED** [review]
Hi, thanks for the contribution! Could you check for 5.1 with `#if ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION == 1`?

**Comment by ameaninglessname** [comment]
> 
Done, I changed the condition to `#if ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 1`, and was thinking of changing it further to `#if ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 1`.

And there are some white spaces removed by the IDE, hope it would be fine.

**Review by mastercoms — APPROVED** [review]

**Comment by mastercoms** [comment]
Thanks, merged!

**Comment by Liyaa** [comment]
Hi，I'm a little confused, why does this place always return false?
image

As a result, we can no longer checkin single file, and cannot select partial files in the submit box, such as:
image

Can you tell me the reason? A lot of thanks!

**Comment by ameaninglessname** [comment]
> Can you tell me the reason? A lot of thanks!

It should be copied from :
https://github.com/EpicGames/UnrealEngine/blob/74a01ed18ad9d6a9347a3238e9262348d206c27a/Engine/Plugins/Developer/GitSourceControl/Source/GitSourceControl/Private/GitSourceControlProvider.cpp#L278

update:
it was introduced in:
https://github.com/EpicGames/UnrealEngine/commit/286e2234bfb777de45ffaef62da6601b46645812

**Pull request merged**
