### PR TITLE
Diff assets against their revision on origin/develop

### PR DESCRIPTION
**Pull request by TheEmidee**
This PR adds a context menu extension in the content browser to allow to diff several assets against their counterparts on origin/develop

This is useful in a gitflow workflow for example

### CODE REVIEW

**Comment by mastercoms** [comment]
Could you instead use status branch functionality for this? Get status branches and get the last element.

**Review by windystrife — APPROVED** [review]

**Comment by TheEmidee** [comment]
@mastercoms yes sure. I'll be in holiday for 2 weeks starting this weekend. I'll do that when I'm back

**Comment by mastercoms** [comment]
Are you still planning to do the status branch changes?

**Comment by TheEmidee** [comment]
Hi !

Sorry I completely forgot about that PR.

I've just updated the code to generate as many context menu items as there are status branches registered in the source control provider

**Review by mastercoms — CHANGES_REQUESTED** [review]
Could you please resolve conflicts with the reformat done on the utils header. Then also for the menu entries, I would prefer that you localize the part without the branch name and then format the branch name in.

**Pull request merged**
