### PR TITLE
Submodule support

### PR DESCRIPTION
**Pull request by Louspirit**
Adding support to do all git operations for GIT Submodules that would be located in the _Plugins_ folder.
The use case is sharable content plugins you would maintain outside the project repository.

See https://github.com/SRombauts/UEGitPlugin/issues/44

### CODE REVIEW

**Comment by mastercoms** [comment]
Thanks for this! Looks feasible on first glance, will review it hopefully later in this week!

**Comment by Louspirit** [comment]
I fixed a compilation error. Made a push force using a rebase interactive to keep one commit.
It should be ready to merge now.

**Comment by mastercoms** [comment]
Hi sorry, will have to do this in February, got swamped with a lot of unexpected work

**Comment by Louspirit** [comment]
Hello, just coming for news 😁

**Comment by mastercoms** [comment]
Hi, I've been getting really behind D: I'm really trying to catch up on my Unreal Engine work but I will have reduced time until maybe May or June

**Comment by ameaninglessname** [comment]
> Hello, just coming for news 😁

image
Just rebased your changes to latest locally, it works on sub-modules, and blueprint diif.
(though I didn't think I changed any of these "PropertyAccess" things, it should be the mistake of blueprint diff tool)

**Comment by ameaninglessname** [comment]
image

**Comment by Louspirit** [comment]
As suggested by @ameaninglessname, I did a rebase with the latest stuff, removing conflicts. You can do the merge when you're ready @mastercoms

**Review by mastercoms — APPROVED** [review]

**Pull request merged**
