### PR TITLE
Fix git plugin getting in the way of the cook step when clicking "Coo…

### PR DESCRIPTION
**Pull request by Murazaki**
…k Content" in editor

### CODE REVIEW

**Comment by mastercoms** [comment]
Aren't source control plugins used in some commandlets?

**Comment by Murazaki** [comment]
Then `Editor`?  Why are you using `UncookedOnly` though in the first place ?

**Comment by mastercoms** [comment]
Fixing #38

**Comment by Murazaki** [comment]
Great, the closing module thread error blocks cook in `Editor` Type

```
UATHelper: Packaging (Windows): Execution of commandlet took:  37.98 seconds
UATHelper: Packaging (Windows): LogShaderCompilers: Display: ================================================
UATHelper: Packaging (Windows): LogShaderCompilers: Display: === FShaderJobCache stats ===
UATHelper: Packaging (Windows): LogShaderCompilers: Display: Total job queries 0, among them cache hits 0 (0.00%)
UATHelper: Packaging (Windows): LogShaderCompilers: Display: Tracking 0 distinct input hashes that result in 0 distinct outputs (0.00%)
UATHelper: Packaging (Windows): LogShaderCompilers: Display: RAM used: 0.00 MB (0.00 GB) of 1638.40 MB (1.60 GB) budget. Usage: 0.00%
UATHelper: Packaging (Windows): LogShaderCompilers: Display: === Shader Compilation stats ===
UATHelper: Packaging (Windows): LogShaderCompilers: Display: Shaders Compiled: 0
UATHelper: Packaging (Windows): LogShaderCompilers: Display: Jobs assigned 0, completed 0 (0.00%)
UATHelper: Packaging (Windows): LogShaderCompilers: Display: Time at least one job was in flight (either pending or executed): 0.00 s
UATHelper: Packaging (Windows): LogShaderCompilers: Display: ================================================
UATHelper: Packaging (Windows): LogModuleManager: Warning: GetModule racing against IsReady: GitSourceControl
UATHelper: Packaging (Windows): LogWindows: Error: appError called: Assertion failed: Module [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Modules\ModuleManager.cpp] [Line: 393]
UATHelper: Packaging (Windows): GitSourceControl
UATHelper: Packaging (Windows): LogThreadingWindows: Error: Runnable thread Background Worker #13 crashed.
UATHelper: Packaging (Windows): LogWindows: Error: begin: stack for UAT
UATHelper: Packaging (Windows): LogWindows: Error: === Critical error: ===
UATHelper: Packaging (Windows): LogWindows: Error:
UATHelper: Packaging (Windows): LogWindows: Error: Assertion failed: Module [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Modules\ModuleManager.cpp] [Line: 393]
UATHelper: Packaging (Windows): LogWindows: Error: GitSourceControl
UATHelper: Packaging (Windows): LogWindows: Error:
UATHelper: Packaging (Windows): LogWindows: Error:
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff7544c515 UnrealEditor-Core.dll!FModuleManager::LoadModuleChecked() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Modules\ModuleManager.cpp:393]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff4799f5de UnrealEditor-GitSourceControl-0005.dll!GitSourceControlUtils::ParseFileStatusResult() [---------\Plugins\UEGitPlugin\Source\GitSourceControl\Private\GitSourceControlUtils.cpp:1073]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff479a123c UnrealEditor-GitSourceControl-0005.dll!GitSourceControlUtils::ParseStatusResults() [---------\Plugins\UEGitPlugin\Source\GitSourceControl\Private\GitSourceControlUtils.cpp:1221]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff479ac41c UnrealEditor-GitSourceControl-0005.dll!GitSourceControlUtils::RunUpdateStatus() [---------\Plugins\UEGitPlugin\Source\GitSourceControl\Private\GitSourceControlUtils.cpp:1453]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff4798d9b1 UnrealEditor-GitSourceControl-0005.dll!FGitFetchWorker::Execute() [---------\Plugins\UEGitPlugin\Source\GitSourceControl\Private\GitSourceControlOperations.cpp:689]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff47988f55 UnrealEditor-GitSourceControl-0005.dll!FGitSourceControlCommand::DoThreadedWork() [---------\Maya\Plugins\UEGitPlugin\Source\GitSourceControl\Private\GitSourceControlCommand.cpp:46]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff753ed863 UnrealEditor-Core.dll!FQueuedThreadPoolWrapper::FScheduledWork::DoThreadedWork() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Misc\QueuedThreadPoolWrapper.h:128]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff753d61b4 UnrealEditor-Core.dll!<lambda_2cfb882046ba83e24f4606b279dfb220>::operator()() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\Fundamental\Task.h:504]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff753e3e53 UnrealEditor-Core.dll!LowLevelTasks::TTaskDelegate<LowLevelTasks::FTask * __cdecl(bool),48>::TTaskDelegateImpl<<lambda_2cfb882046ba83e24f4606b279dfb220>,0>::CallAndMove() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\Fundamental\TaskDelegate.h:171]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff7506bbbc UnrealEditor-Core.dll!LowLevelTasks::FTask::ExecuteTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\Fundamental\Task.h:656]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff7506baa6 UnrealEditor-Core.dll!LowLevelTasks::FScheduler::ExecuteTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\Fundamental\Scheduler.cpp:184]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff7504db48 UnrealEditor-Core.dll!LowLevelTasks::FScheduler::TryExecuteTaskFrom<&LowLevelTasks::TLocalQueueRegistry<1024>::TLocalQueue::DequeueGlobal,0>() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\Fundamental\Scheduler.cpp:361]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff7508e762 UnrealEditor-Core.dll!LowLevelTasks::FScheduler::WorkerMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\Fundamental\Scheduler.cpp:402]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff7505bab0 UnrealEditor-Core.dll!UE::Core::Private::Function::TFunctionRefCaller<<lambda_0a548c7e497de3cc77a9e48080e1524f>,void __cdecl(void)>::Call() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Templates\Function.h:475]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff751f130b UnrealEditor-Core.dll!FThreadImpl::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\HAL\Thread.cpp:67]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff757a3a52 UnrealEditor-Core.dll!FRunnableThreadWin::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:149]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007fff7579b860 UnrealEditor-Core.dll!FRunnableThreadWin::GuardedRun() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:79]
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007ff88c4826bd KERNEL32.DLL!UnknownFunction []
UATHelper: Packaging (Windows): LogWindows: Error: [Callstack] 0x00007ff88dd8dfb8 ntdll.dll!UnknownFunction []
UATHelper: Packaging (Windows): LogWindows: Error:
UATHelper: Packaging (Windows): LogWindows: Error: Crash in runnable thread Background Worker #13
UATHelper: Packaging (Windows): LogWindows: Error: end: stack for UAT
UATHelper: Packaging (Windows): Took 54,9522075s to run UnrealEditor-Cmd.exe, ExitCode=3
UATHelper: Packaging (Windows): ERROR: Cook failed.
UATHelper: Packaging (Windows):        (see C:\Users\-----\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Apps+Epic+Games+UE_5.1\Log.txt for full exception trace)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 2m 40s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Error: Unknown Cook Failure
```

**Comment by mastercoms** [comment]
I need to do a pass for thread safety on module management, thanks for getting a stack trace

**Pull request closed without merging**
